seagle0128/doom-modeline

doom-modeline.el

As the title says with this variable you can choose what executable for python will be used, if the value is nil no version will be shown.

Add variable for the python-version

---

doom-modeline.el

Show multiple cursors count in the `modeline` panel similar to anzu, iedit.

Show multiple cursors count in the modeline panel

---

doom-modeline.el

I actually have no idea why this would happen, but if the file is not byte-compiled beforehand, there will be quite a few warnings of `Unused lexical var` each time when the `doom-modeline-def-modeline` is called.
If users install this package through `package.el`, this will not cause any problem. However, if users install this package manually, this will be very annoying.
Note that the similar thing has been done in Doom Emacs in this commit: https://github.com/hlissner/doom-emacs/commit/70e0280db39b1ee8f2f4184b21c03260210392f4.
By the way, thank you for bringing and maintaining this awesome package.

Stop byte-compiling modeline format functions

---

doom-modeline.el

I don't use anzu, I occasionally get this error "Symbol’s function definition is void: anzu--reset-status" coming from doom-modeline. This PR is an attempt to fix this.

Don't try to call anzu functions if anzu isn't installed

---

doom-modeline.el

Its absence results in a compile error when using borg-build:
In toplevel form:
doom-modeline.el:314:1:Warning: Unused lexical argument ‘key’
In doom-modeline-set-modeline:
doom-modeline.el:314:50:Warning: ‘(modeline (doom-modeline key))’ is a
malformed function
doom-modeline.el:322:22:Warning: reference to free variable ‘modeline’
In doom-modeline-set-selected-window:
doom-modeline.el:390:49:Warning: ‘(win (frame-selected-window))’ is a
malformed function
doom-modeline.el:393:41:Warning: reference to free variable ‘win’
In end of data:
doom-modeline.el:1249:1:Warning: the function ‘when-let’ is not known to be
defined.
Which ultimately results in an error disrupting proper startup:
Invalid function: (modeline (doom-modeline key))

Fix: require subr-x (needed for when-let)

---

doom-modeline.el

Since executable-find cannot handle a nil argument then doom-modeline-python-executable should not be passed if it is set to nil.

Fix python-mode when executable is nil

---

doom-modeline.el

Depending on configuration, `projectile-project-root' raises an error if there
is no project available. This behaviour almost renders Emacs unusable outside
of projects as `doom-modeline-project-root' gets called upon every redisplay of
the modeline, which then causes the error.
This fix just ignores errors thrown by `projectile-project-root' and returns
`nil' instead, which is what we expect anyway.

Fix calling `projectile-project-root'.

---

doom-modeline.el

This PR solves this issue: `widen` doesn't remove the "narrowed" file state icon.
To reproduce the issue:
- M-x narrow-to-defun -- the "narrowed" file state icon is displayed in the modeline
- M-x widen -- the "narrowed" file state icon is still displayed in the modeline, but I expect it not to be there because the buffer is not narrowed anymore

Update file state icon after widening

---

README.md
doom-modeline.el

Some users of parrot are fans of doom-modeline (see dp12/parrot#1). If we could add a parrot segment to doom-modeline, I think it'd be much appreciated!

Add party parrot segment

---

README.md

According to use-package manual
> If you aren't using :commands, :bind, :bind*, :bind-keymap, :bind-keymap*, :mode, :interpreter, or :hook (all of which imply :defer ...

Remove unnecessary use-package :defer

---

doom-modeline.el
doom-version-parser.el
test/doom-version-parser-test.el

This PR is meant to address issue #90.
In this PR, I changed the `doom-modeline-env-update` command to use a new non-blocking function, `doom-version-parser--get`. I also added two more local variables to doom-modeline. One is `doom-modeline-env-command-args` which is a list of strings needed to get a program to print out version information. The other is `doom-modeline-env-parser` which is a elisp function that is used to parse the resultant string and return the version number of the program. Because of these changes required a significant rewriting of the mode hooks for modes that tracked version information.

Make programming environment version parsing asynchronous

---

doom-modeline-core.el
doom-modeline-segments.el
doom-modeline.el

This is a new segment for `mu4e-alert' that shows unread emails in the modeline. For now, we enable it where github notifications are enabled and make it a simple number.
When experimenting with adding an email icon, the modeline seemed a bit too crowed so there is no icon for this number. We can perhaps add a flag later to toggle that. Alternatively, we could expose more options for the `doom-modeline-mu4e-formatter' that could tweak the number and the icon.

mu4e: add new segment that shows unread emails

---

doom-modeline.el

This is required for those of us not using mu4e, otherwise, you get a void variable error.
This may not be the right way to do this, but without this, I cannot load doom-modeline.

Initialize mu4e-alert-modeline-formatter

---

doom-modeline-segments.el

I've moved the checker segment to a different location. In buffers where `flycheck-mode` and `flymake-mode` are disabled (or have no checkers), a large gap is left behind.
This PR fixes this.

Hide checker segment when disabled/empty

---

doom-modeline-segments.el

A search in one buffer is displayed as matches across all buffer modelines:
This PR ensures anzu state is made buffer-local:

Fix matches segment mirroring across all buffers

---

doom-modeline-segments.el

Reverts seagle0128/doom-modeline#125

Revert "Fix matches segment mirroring across all buffers"

---

doom-modeline-segments.el

If we wait to unset `anzu-cons-mode-line-p` until the first time the anzu sub-segment runs, then we create an opportunity for anzu to inject its own indicator into the modeline.
For example, in Doom, the dashboard is the first buffer you see. It displays the project modeline which has no matches segment. That means `anzu-cons-mode-line-p` won't be unset until I open another buffer with a modeline that possesses the segment. If I conduct a search in the dashboard before doing this...
It's an obscure race/edge case, but I think it's best we tell anzu not to do this as soon as possible.

Prevent anzu from injecting itself into modeline

---

doom-modeline-segments.el

To follow up #125, this fixes the original problem as well as the side effects with anzu-query-replace.

Fix matches segment mirroring across all buffers (part 2)

---

doom-modeline-segments.el

After the recent refactor of mu4e segment. There's error in message buffer
``` 
Error during redisplay: (eval (doom-modeline-segment--mu4e)) signaled (wrong-type-argument number-or-marker-p #(" Mail [11] " 1 5 (display (image :type xpm :file "/usr/local/Cellar/emacs-plus/HEAD-d6b3e5b/Emacs.app/Contents/Resources/etc/images/letter.xpm" :ascent center) face nil help-echo "You have 11 unread emails
```

fix mu4e-alert-mode-line numberp error

---

doom-modeline-segments.el

This reverts commit b29ce18e6853ed80f73a0b6cda869a8cbedb9b0e.
https://github.com/seagle0128/doom-modeline/pull/130

Revert "fix mu4e-alert-mode-line numberp error"

---

doom-modeline-core.el

Per the official docs of select-window if you want to call a function every time a window is selected you should use buffer-list-update-hook. It automatically does The Right Thing and gets called only when necessary.
The correction isn't theoretical either, advising select-window can lead to nasty feedback loops as in Alexander-Miller/treemacs#369.
Btw some of the other parts of advice in that sections could be replaced with after-make-frame-functions and delete-frame-functions.

Use buffer-list-update-hook instead of advising select-window.

---

doom-modeline-core.el

The `doom-modeline--buffer-file-name-relative` routine treats `project-root` as part of `relative-path`, so it doesn't get the proper face.  The `doom-modeline--buffer-file-name` routine already supports this style with the appropriate arguments, so we use that instead.

Highlight project-root for relative-from-project style

---

doom-modeline-segments.el

Adds support for evil-mc. Also improves the look of the segment.
Evil-mc only: when cursors are frozen the segment is blue. When they are active, it's green

Add evil-mc support to multiple-cursors segment

---

README.md
doom-modeline-core.el
doom-modeline-env.el
test/doom-modeline-env-test.el

**Goal of this PR**
The primary goal of this PR is to have the env mode-line segment initialized as late as possible (on `hack-local-variables-hook`) so users can customize it with file/dir-local variables.
**Other benefits**
* A macro that makes adding support for more languages a bit easier.
* The ability to customize all the executables.
* Use named hooks to allow users to remove them if they desire.
* Adds `doom-modeline-before-update-env-hook` and `doom-modeline-after-update-env-hook` hooks for more opportunities to change or react to the version string.
* Segment displays `...` while waiting for the new version string.
**Why I create this PR**
I wanted to inject support for conda.el, pyvenv.el and `python-shell-virtualenv-root` to the python segment, but the env display was …

Refactor env system

---

doom-modeline-segments.el

Using `doom-modeline-eldoc-bar` when active instead of `mode-line-inactive`.
The same logic is used for `evil-mc-cursor-list` beneath the handling of `multiple-cursors-mode`.

Don't use inactive face for active multiple-cursors matches context

---

doom-modeline-segments.el

Using `(mc/num-cursors)` instead of relying on what the modeline of multiple-cursors is.
Before this change nothing was shown in the "matches" section of the modeline.

Show number of multiple cursors correctly

---

doom-modeline-env.el

Prevents file-missing errors when invoking executables that don't exist.

No-op if env executable doesn't exist

---

doom-modeline-core.el
doom-modeline-segments.el

`font-lock-doc-face` can clash with `mode-line` colors and changing `font-lock-doc-face` to match `mode-line` may not be desirable. This adds a face inheriting `font-lock-doc-face`, making it user configurable.

Make uses of font-lock-doc-face configurable

---

doom-modeline-segments.el

Follow up to #163, simply replaces calls to `flymake--severity` with direct calls to `flymake--lookup-type-property`.

Make #163 compatible with flymake in Emacs 26

---

doom-modeline-core.el
doom-modeline-segments.el

I encountered some regressions, so here's some fixes and more.
* Fix for `Format specifier doesn't match argument type` error (4992a27)
* Fixes to a regression resulting to loss of color for some segments (de932ea, 88550d3)
* Try to get all the whitespace in segment separators propertized, so that they get the `mode-line-inactive` face when using `helm-M-x` (and others I guess) (8be3a04, 768083d)
* Change to checker text behaviour when the checker is running (aceb087)
Some of the changes might be unpleasant so take what you like, let me know if you want something changed.

Various fixes

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

Just a small change to provide an option to set icon before workspace name instead of # sign.
I picked material's aspect_ratio icon. Weird choice maybe, but it looks nice, I think.

Add icon for persp-name segment

---

doom-modeline-core.el

Some package may alias it (or define a enhance version) before the loading of
`doom-modeline` (AFAIK, doom-emacs do this in the configuraion https://github.com/hlissner/doom-emacs/blob/c3c282f0a4f99945288f9e656b7684c0e970b630/core/core-lib.el#L14)
Use `eval-and-compile`, allow byte-compiler see through the form, is better than
using `with-no-warnings` to suppress it rigidly.

When `if-let*` or `when-let*` was defined, don't do alias for it.

---

doom-modeline-env.el

This fixes an issue where `apropos-documentation` iterates over obarray (with `mapatoms`). The `(concat ...)` and `(format ...)` forms are left unevaluated in some of these symbol's definitions, which causes the following error:
```
Debugger entered--Lisp error: (wrong-type-argument stringp concat)
insert-file-contents(concat)
apropos-documentation-check-elc-file(concat)
apropos-documentation-internal((concat "A function that returns the shell command and arguments (as a list) to\n" "produce a version string."))
#f(compiled-function (symbol) #<bytecode 0x490349>)(doom-modeline-env-python-command)
mapatoms(#f(compiled-function (symbol) #<bytecode 0x490349>))
apropos-documentation(("test") nil)
funcall-interactively(apropos-documentation ("test") nil) …
```

Evaluate docstrings in doom-modeline-def-env

---

doom-modeline-segments.el

Or else the cursor jumps after overlays become empty.
here is a full frame reproducing video https://la.wentropy.com/doXC.webm

inhibit bogus cursor jump.

---

doom-modeline-segments.el

If there is no checker text (i.e. no errors), you were ending up with
two spaces after the checker icon. Fix by moving the second space into
the "text" conditional.
Before:
After:

Fix double space after "checker" segment.

---

doom-modeline-segments.el

doom-modeline is using various Eglot internals to display its Eglot
segment. One of those internals, `eglot--current-server`, recently changed
so that it now triggers a cache variable, `eglot--cached-current-server`,
to be set.
The hook used by doom-modeline is run during shutdown, after the buffer
becomes unmanaged by Eglot, but before all of its internal state has
been updated. The call to `eglot--current-server` then triggers the cache
variable to be set to an outdated value, which remains after shutdown
completes.
Any further calls to Eglot will end up seeing the incorrectly cached
value, which causes all kinds of breakage.
Note that, with or without this fix, the implementation relies on Eglot
internals and is likely to be fragile.
See joaotavora/eglot#342 for more context.

Fix Eglot update hook breaking Eglot shutdown

---

doom-modeline-env.el
doom-modeline-segments.el

Adds a customizable option to toggle displaying the default perspective's name
on the modeline. Updates `doom-modeline-update-persp-name` to respect it.
Fixes #261

Introduce `doom-modeline-display-default-perspective-name`

---

README.md
doom-modeline-core.el
doom-modeline-segments.el
doom-modeline.el

In case it's useful: 
This patch introduces `doom-modeline-continuous-word-count-modes`, a customizable list of major modes in which a word count is displayed continuously. Also applies to derived modes. Respects `doom-modeline-enable-word-count`.
```lisp
;; Major modes in which to display word count continuously.
;; Respects `doom-modeline-enable-word-count'.
(setq doom-modeline-continuous-word-count-modes '(text-mode))
```

Add continuously displayed word count segment.

---

README.md
doom-modeline-core.el
doom-modeline-segments.el
doom-modeline.el

A rather simple implementation of a `Gnus` mail notification handler.
I created it so that if enabled, it also fetches new mails automatically all 2 minutes per default. I think people might like this because otherwise they need another plugin or custom code in their config. It could also be deactivated per default, but since notifications are only shown when gnus runs and since I couldn't find any "better" way to search for mails I figured this is probably the standard way for most people anyways.
The variable can be modified to change the timeout between fetches, or to disable any automatic updates by setting it to `nil`.
Also I coldheartedly copied the `unread mail counter lambda` in the function `doom-modeline-update-gnus-status` from …

Add basic Gnus support without any other dependency than gnus

---

doom-modeline.el

The doom modeline is not set properly for the `*Messages*` and `*scratch*` buffers.
It follows 95809a1b04ebdbc047e45f5bbc95fb6b621e208d: `buffer-live-p` doesn't appear to work with buffer names, but directly with buffers. It means that `(buffer-live-p bname)` always return nil.
Using `(get-buffer bname)`  ensures the buffer existence test is done properly.

Fix bug in testing buffers existence

---

doom-modeline-segments.el

If doom-modeline-major-mode-icon is nil, we should not show the
file-directory icon for buffer-default-directory segment.

Check before displaying icon for buffer-default-directory

---

README.md

Fix issue with use-package installation

---

README.md
doom-modeline-core.el
test/doom-modeline-core-test.el

Hi, I could'nt find any other way to show full buffer-info. Is this PR alright?

buffer-info: add `truncate-nil` style

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

By default the persp name is displayed with a folder icon. This patch makes the
icon toggleable via `doom-modeline-persp-icon`.
Before:
After:

Make persp mode indicator icon toggleable

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

Some description， fix #342.
**Modification**
1. fix `gethash` error
2. fix `seq-contains-p` in `seq.el`
3. add readme description
**Note**
1. I use `eval` instead of coding an expanded-macro, which is more compatible in my opinion.
2.  I __ONLY__ test it on Emacs 26.3 with `seq` and `gnus`. 
- `seq.el` has not `seq-contains-p` on my emacs version 26.3
- `gnus-group-unread` defination is different from the HEAD(2b308857677e983ca4eaedc36438ed94aadf9e65)
3. add some description in readme

[FIX] gnus update status error

---

doom-modeline-segments.el

Fixes #327 
As discussed [here](https://github.com/seagle0128/doom-modeline/issues/327#issuecomment-635456086), we need to update other buffers when debug session is started/terminated. 
This is not the best way to handle the problem but it's a start I think.

[debug] fix modeline color change for all buffers

---

doom-modeline-core.el
doom-modeline-segments.el
doom-modeline.el

Add a REPL segment: 
Currently, the REPL segment is activated when `cider-mode` is enabled or connected.
On the future we can use the same segment for other repl features from other languages too.
Closes https://github.com/seagle0128/doom-modeline/issues/347#issuecomment-640240103

Add repl segment for CIDER

---

doom-modeline-core.el

Just a small refactor that makes this more readable IMO.
Thanks for the modeline! Fantastic looking without slowing things down.
~ Nicholas Vollmer

Refactor: doom-modeline-propertize-icon use cl-destructuring-bind

---

doom-modeline-core.el
doom-modeline-segments.el

Instead of using `tab-width` for space indentation size, the correct indentation size variable is tried detected per major mode. If nothing can be found, it will fall back to `tab-width` as before.
It is based upon [`editorconfig-indentation-alist`](https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L165) but is used to read indentation levels instead of setting them. When multiple variables are specified, they will be tried resolved in the given order.

Improve indent info by showing correct indent size by major mode

---

doom-modeline-segments.el
doom-modeline.el

This was requested in https://github.com/RyanMillerC/poke-line/issues/9 and is better supported directly in doom-modeline itself like nyan-mode etc.

Add support for poke-line in buffer position segment

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

I'm not sure if my "abuse" of the `when-let` to check the option is considered
good or bad in eslip, but seems to work. I'm happy to refactor though if it's
considered bad :)

Add option to show/hide workspace-name in modeline

---

doom-modeline-segments.el

[Boon](https://github.com/jyp/boon) is a modal mode for Emacs. This
commit adds support for Boon in the modal segment.
Boon has four states:
- Command (like Evil's normal)
- Insert
- Special (mostly pass-through, much like Evil's Emacs mode)
- Off, used when Boon really doesn't know what to do. There is no real
equivalent in Evil; this commit uses the same face as Evil's
operator state for this one. It's arbitrary, but it probably doesn't
matter too much.

Add support for Boon modal states

---

doom-modeline-env.el

The python environment will be shown in the following priority:
pipenv > pyenv > `doom-modeline-env-python-executable/python-shell-interpreter/python`

Add `pyenv version-name`

---

doom-modeline-segments.el

I've made some changes to add [meow](https://github.com/DogLooksGood/meow) indicator.
Is there some rules that modal icon will not be displayed in `dired`? I want the indicator available for all modes, since there's special mode, KEYPAD mode in Meow is used for executing commands.
@meziberry provides me some code to add indicator as a standalone segment, but it seems not follows `doom-modeline`'s design. So I asked here.
Please review the changes.

Add Meow indicator

---

doom-modeline-core.el
doom-modeline-env.el
doom-modeline.el

Hello.
Thanks for making this package.
I stumbled upon a few typos while skimming through the code.

fix: typos in comments and docstrings

---

doom-modeline-core.el
doom-modeline-segments.el

There is a face for the number part of
notifications (`doom-modeline-unread-number`), however, none for the
notification itself. For symmetry, we introduce
`doom-modeline-notification` as a face for notifications. We also set
the default value to `doom-modeline-warning` to keep the previous
behavior.

Add face for notifications

---

doom-modeline-core.el
doom-modeline-segments.el

Switch from an XPM to a PBM bitmap: PBM is easier to generate and easier
for Emacs to decode. Emacs has PBM support built-in so it's always
available (keep the `image-type-available-p` check in case this changes).
Stop creating a temporary list-of-lists to iterate over.
Rename `doom-modeline--make-xpm` to `doom-modeline--make-image` because
it's no longer creating an XPM, and the type of the bitmap should not
matter to callers.

Simplify image creation

---

doom-modeline-core.el
doom-modeline-segments.el

Only showing the buffer encoding and EOL style when they are
interesting (not at their default values) makes them stand out more when
needed, and frees up space when not. Users currently cannot hide the
coding-system and EOL segments separately, and would have to watch for
changes to `buffer-file-coding-system` to toggle visibility. Since
doom-modeline reads these values already anyway, we can easily add
support.
Add a new value `'nondefault` for `doom-modeline-buffer-encoding` to
enable this feature.
Add two new settings to set the default. Detecting the user's defaults
is tricky: Emacs does not use a single variable for the default coding
system but a prioritized list, and hooks can (and do, on Windows) change
the defaults. For now, hardcode reasonable "default defaults" and allow
the …

Support hiding buffer encoding when at default

---

doom-modeline-env.el

Thank you for your great work.
Let me give you a small patch for python version display.
This reverts "pipenv run python --version" command generation code
removed by #391 patch.
e898c0d master
doom-modeline-env.el (doom-modeline-def-env python ..)
```
(pipenv-project-p)
=> "~/"
doom-modeline-env-python-executable
=> "python"
python-shell-interpreter
=> "jupyter"
(funcall (lambda () (cond ((and (fboundp 'pipenv-project-p)
(pipenv-project-p))
(list "pipenv" "run"))
((executable-find "pyenv") (list "pyenv" "version-name"))
((list (or doom-modeline-env-python-executable
python-shell-interpreter
"python")
"--version")))))
=> ("pipenv" "run")
```
a73cc3d Rewrite env system
doom-modeline-env.el (doom-modeline-def-env python ..)
```
(pipenv-project-p)
=> "~/"
doom-modeline-env-python-executable …
```

Fix doom-modeline-env command to display python version under pipenv

---

doom-modeline-segments.el

This is a small graphical indicator showing the rough size of and
position in the current buffer. It is not used by default in any
modeline, but is intended to be usable as a replacement of the "bar"
segment.
To avoid performance problems, cache the HUD images as window
parameters. When rendering the modeline, we check if the buffer
position (or size) has changed enough to change the image, and reuse the
image if not. This check should be similar in performance to rendering
buffer size or position. Changing bar width or height forcibly
invalidates all cached images, so they get redrawn as the modeline in
each window is rendered.
This only adds the segment. To use it, define a new modeline.

Add a "hud" segment inspired by powerline

---

doom-modeline-core.el

This might fix the issue raised on #442 (`(wrong-type-argument wholenump -342)`).

Add a minimum height for the hud's middle part

---

doom-modeline.el

Instead of (de)activating the modeline for the current buffer and a couple of special-cased buffers, (de)activate it for all open buffers. This:
1. Ensures that enabling/disabling the modeline at any point sets the modeline everywhere.
2. We actually catch all buffers at start, regardless of startup order. Without this patch, the "*Async-native-compile-log*" doesn't get a modeline.

(De)Activate modeline for all existing buffers

---

doom-modeline-segments.el

I add [sml-modeline](https://melpa.org/#/sml-modeline) to buffer-position of doom-modeline.

Add sml-modeline to buffer-position

---

doom-modeline-segments.el

Recently the [change in vc-git in emacs](https://github.com/emacs-mirror/emacs/commit/3572613550f5d1d0b3392dbc809b32f3989e2981)
broke modeline state in remote files as it prepends a string in the
beginning and cannot retrieve relative file path to pass as git command
argument.
The fix here ensures that the prefix in the beginning of the file path
doesn't break the `(vc-state)` command by passing local file name of the
remote files.
Fix #463

Use `file-local-name` to get VC state

---

doom-modeline-segments.el

Currently it is not possible to use flymake with doom-modeline, as the variable `flymake--backend-state` was renamed to `flymake--state` in flymake.el
s.a. https://github.com/emacs-mirror/emacs/commit/6e100869012da9244679696634cab6b9cac96303
This fix replaces all references in doom-modeline-segments.el accordingly.

rename flymake--backend-state to flymake--state

---

doom-modeline-segments.el
doom-modeline.el

When follow-mode is enabled for a buffer, this will show a segment left
of buffer-info (which contains the file name) like "Follow M/N", where N
is the total number of follow windows for this buffer and M is the index
of the selected window.

Add modeline segment for follow-mode

---

doom-modeline-segments.el

Otherwise, I get the error `Two bases given in one event`.

doom-modeline-update-flycheck-text: literal vector

---

doom-modeline-segments.el

The variable signaling the current mode state changed in Nov. 2021 at this commit:
https://github.com/xahlee/xah-fly-keys/commit/c6a7367afa0dbdb734319268f4e0bb708f4fec11#diff-0e4ccd274fc24cf949be60a562eec725e12c88f11eb005c6821c9fd0fe03aba2
This renaming fixes it.

changed 'xah-fly-insert-state-q' to 'xah-fly-insert-state-p'

---

doom-modeline-core.el

As of
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=86969f9658,
the return value of project-current is shaped differently.

Ensure compatibility with newer project.el

---

doom-modeline-core.el
test/doom-modeline-core-test.el

The project.el shipped with Emacsen <= 27 do not actually have
`project-root` at all. We account for this by restoring the old
behavior of doom-modeline--project-root in an else branch.
Since the testing suite installs a recent
project.el on Emacsen >= 26, test the old behavior only on Emacsen <
26.

Actually account for stale versions of project.el

---

doom-modeline-core.el
doom-modeline-env.el
doom-modeline-segments.el

* doom-modeline-core.el (doom-modeline-def-modeline):
* doom-modeline-env.el (doom-modeline-env--command-args)
(doom-modeline-env--parser, doom-modeline-env--get):
* doom-modeline-segments.el
(doom-modeline-before-github-fetch-notification-hook): Fix
warnings about wrong usage of unescaped single quotes in
docstrings issued by Emacs 29.

Fix warnings about single quotes in docstrings

---

doom-modeline-core.el

First, I exempted natively compiled modeline segments from being byte-compiled, as this produces an error during native compilation. Afterwards, I changed the `fset` to a `defun` so that the lambdas would be compiled by the native compiler.

Allow modeline segments to be natively compiled.

---

doom-modeline-core.el

* doom-modeline-core.el (doom-modeline-buffer-modified): Escape
quotes in the docstring.
(doom-modeline-panel): Reword the docstring slightly to be less
than 80 characters wide.

Silence the compiler

---

doom-modeline-core.el
doom-modeline-segments.el
doom-modeline.el

增加doom-modeline 对于 display-time-mode 的原生支持以取代原来的misc-info中自带的`display-time-string`。以下是效果图：

add doom modeline support for display-time-mode

---

doom-modeline-core.el
doom-modeline-segments.el

Hello,
I've added an option to reverse the change in https://github.com/seagle0128/doom-modeline/commit/81666b9b142d091a46d19e43ce08061b9dca973b.
I think it's a reasonable request to hide the misc segment if the modeline is inactive. For instance, perspective.el adds its segment there, which is enough to show only once on a particular frame.

[Feature] New option doom-modeline-display-misc-in-all-mode-lines

---

doom-modeline-segments.el

I found myself not-entirely-happy with the current set of flycheck status icons, so I asked around and presented a few alternatives. In the end it seems there's a near-consensus among the ~half dozen people who responded that the change in this PR is an improvement over the current state of affairs.
Here are some comparison screenshots, and some relevant quotes from the discussion.
**Current**
**Consensus improvement**
**Quotes from the discussion**
> Hourglass means 'background process happening' to me
> I'd probably stick with the hourglass for the win3.1 nostalgia
> favourites for processing: hourglass
**Current**
**Consensus improvement**
**Quotes from the discussion**
> (4 upvotes on this image, all the rest received 0)
> favourite for errors: exclamation-mark-in-a-circle (the other …

Tweak flycheck segment running/finished icons

---

doom-modeline-segments.el

Without this patch only the name of first the visited node when `(info)` is invoked will be displayed in the modeline. When further info nodes are navigated the buffer name in the modeline remains the same, hence showing wrong information.

Update the buffer name when the current Info node changes

---

doom-modeline-core.el

* doom-modeline-core.el (doom-modeline-buffer-modified): Fix warning about setting attribute `:background' to nil value is invalid.

Use unspecified instead of nil in `defface'

---

doom-modeline-segments.el

commit https://github.com/seagle0128/doom-modeline/commit/5d9c20aed929398d79cf847c2d7b14b0bfe3cb99 break `doom-modeline-modal-icon` `nil` condition.

Fix: doom-modeline-modal-icon nil condition

---

doom-modeline-segments.el

The `ICON` and `UNICODE` arguments were outside of `doom-modeline--boon`, so `when` always returned "🍵".

Fix boon mode-line segment

---

doom-modeline-core.el

Error signals that there's something terribly wrong, and while you should probably *save* that modified buffer, warning styling seems like a much more appropriate indication of concern.
For reference, I have overridden this in my own config, and I've seen one or two people in the Doom discord confused and thinking that there was something wrong because the file name had gone error-red in the modelling. I doubt this is a common issue, but it helps confirm in my mind that this is a worthwhile QoL change.

Make buffer-modified face inherit from warning

---

doom-modeline-core.el

To calculate the alightment of rhs, rhs was formated but its result was thrown
away resulting rhs to be unnecessary formated twice. Improved by using the
formted rhs-str. Also avoid unnecessary calculatin when rhs-form is nil.

Improve doom-modeline-def-modeline

---

doom-modeline-segments.el

* doom-modeline-segments.el (doom-modeline--evil-substitute): Silence the compiler about docstring wider than 80 characters. (workspace-name): Assign the return value of `assq-delete-all' to `mode-line-misc-info' which silences compiler warning about value from call to `assq-delete-all' is unused.

Pacify compiler warnings

---

doom-modeline-segments.el

When recording an evil macro, it's useful to verify which register you're recording in.
If you'd rather this not be the default, I'm fine with defaulting it to `nil`, I just personally think this behaviour is more useful ootb.

Add toggle showing the macro register

---

doom-modeline-env.el

1. Skip going through https://github.com/pwalsh/pipenv.el
2. Support finding python via `direnv`

env: Python version lookup improvements

---

doom-modeline-core.el

* doom-modeline-core.el (doom-modeline-buffer-file-name-style): Delete duplicate entry for `truncate-upto-project'.

Pacify the compiler

---

doom-modeline-segments.el

tweleve → twelve
Solves issue loading icon.

Fix typo doom-modeline-time-icon

---

doom-modeline-core.el

Following discussion [here](https://github.com/seagle0128/doom-modeline/issues/643).

expand `doom-modeline-github` docstring

---

doom-modeline-env.el

When using `direnv`, the word "line" is displayed instead of python version as we can see in this screenshot
The problem comes from using single quotes in addition to double quotes in the command used to detect python. We can reproduce the problem in a terminal :

Fix python version with direnv

---

doom-modeline-segments.el

Jsonrpc continuations were reworked on the Emacs master branch to be an alist rather than a hash-table in commit [222f563f136](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=222f563f136c5cb106df1fb94c177fe24c83683f). 
Currently, this change breaks `doom-modeline-update-eglot`, which prevents `eglot` from starting due to a type error from the use of `hash-table-count` on an alist.  The function `jsonrpc-continuation-count` was added to properly get the number of continuations. 
This PR adds a function `doom-modeline--eglot-pending-count` to check if the new function is bound, and if not, fallback to the old method of getting the pending count.

fix: use jsonrpc-continuation-count in doom-modeline-update-eglot

---

doom-modeline-core.el

* doom-modeline-core.el (doom-modeline-check-simple-format): Move `defcustom' after the `define-obsolete-variable-alias' form.  From the docstring:
If CURRENT-NAME is a defcustom or a defvar (more generally, any variable where OBSOLETE-NAME may be set, e.g. in an init file, before the alias is defined), then the
define-obsolete-variable-alias statement should be evaluated before the defcustom, if user customizations are to be respected.

Fix call of `define-obsolete-variable-alias'

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

With the SVG library (bundled as part of Emacs), we can generate an analogue clock for the current time to-the-minute, instead of using the nearest-hour nerdicon.
I've personally been running this variant of the time segment since https://github.com/seagle0128/doom-modeline/issues/577#issuecomment-1267020963, and so am pretty confident this works as we'd hope.
The one thing I wonder about is whether we can make the `svg` library be required only when `doom-modeline--generate-clock` is first called?
Sample screenshot:

Introduce analogue clock time icon

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

Take 2 of #698, resolving the issue noted in https://github.com/seagle0128/doom-modeline/pull/698#discussion_r1515654446.
Now works on my machine _without_ me loading my config :wink:.

Reintroduce analogue clock time icon

---

doom-modeline-core.el
doom-modeline-segments.el

* doom-modeline-core.el (doom-modeline-time-clock-size):
* doom-modeline-segments.el (doom-modeline--generate-clock): Fix typos introduced in commit 311a0c5.

Correct typos in docstrings

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

This add an optional feature to include icons to check-simple-format, it makes doom-modeline fancy and easier to distinguish error types (related to: https://github.com/seagle0128/doom-modeline/issues/639), this implementation no needs to force users add-advices or make a custom (and more complex) segment to modeline.
I would like hear their suggest about this.

Add support for display icons in check-simple-format

---

doom-modeline-segments.el

* doom-modeline-segments.el: Move the definition of custom variables doom-modeline-check-(error|warning|note)-icon after the defintion of the function `doom-modeline-check-text'.  This fixes the compilation error:
Symbol's function definition is void: doom-modeline-check-icon.

Unbreak compilation

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

This PR adds a segment for displaying the currently active Kubectl context and, optionally, the selected default namespace. It sources this information via [`kele.el`](https://github.com/jinnovation/kele.el), which handles config loading and refreshing.
We also hook up the menu map (introduced in jinnovation/kele.el#167 and jinnovation/kele.el#169) to allow users to perform basic Kubernetes management tasks via cursor, e.g. switching contexts/namespaces, starting/stopping proxy servers, etc.

Add Kubernetes segment w/ kele.el

---

doom-modeline-segments.el

Uses `doom-modeline--segment-visible` to additionally hide the Kubernetes segment in narrow-modeline settings, unless user added it to `always-visible-segments`.

segments: k8s: hide when narrow screen

---

README.md

segment name "checker" was changed to "check" in https://github.com/seagle0128/doom-modeline/commit/62890effd01b7424728af8e39e0d9a09e05529a3, but the README still uses "checker" in an example.
This change broke my code to add padding on the right, taken from [here](https://github.com/doomemacs/doomemacs/issues/2967). The [doom emacs docs](https://docs.doomemacs.org/v21.12/modules/ui/modeline/#/troubleshooting/the-right-side-modeline-cut) also still use the wrong name. I'll see if I can also propose a fix over there.
**Edit** nevermind, it's already fixed in the doom-emacs github. The website just hasn't updated yet or something.

docs: checker -> check in README

---

doom-modeline-segments.el

Hello,
First, let me thank you for this awesome package.
This MR adds Evil-like state icons for Meow.

Evil-like state icons for `meow`

---

doom-modeline-segments.el

Instead of allocating a list with N items and returning its length, just keep a tally of the number directly. This can also avoid generating lots of garbage that has to be collected.
The performance impact can be tested with this when using Evil:
```elisp
(benchmark-run 10 ; or some other number of repetitions
(let ((last-kbd-macro [?/ ?. return])) ; initiate an evil search for the pattern "."
(call-last-kbd-macro)))
```
On my machine in a 2.3 MB file, this went from 27.06 seconds (2.7 seconds per iteration) to 25.98 seconds (2.6 seconds per iteration), but before this change I also sometimes experience lockups where the search inexplicably takes several times longer.

perf: calculate anzu count faster and with less memory

---

doom-modeline-core.el
doom-modeline-segments.el

After #729 the option to not shorten IRC buffers. This PR documents the option and enhances the existing documentation
related to it.
Also mention rcirc as supported IRC mode for buffer segments.

Improve IRC buffer Stylize defcustom and enhance documentation

---

doom-modeline-segments.el

This PR does exactly what the title says. This feature was added in [this commit](https://github.com/seagle0128/doom-modeline/commit/ef8038140fc76d96614fc8dd34a8c85cd4843b0c) but the author directly called the default function instead of calling the function stored in the custom variable.

Properly call `doom-modeline-vcs-display-function`

---

doom-modeline-segments.el

When the file associated with the current buffer is modified outside Emacs, a new icon is used to indicate that the buffer needs to be reverted.  This feature is from smart-mode-line.

feat: Show file modification status outside Emacs.

---

doom-modeline-core.el
doom-modeline-env.el
doom-modeline-segments.el

* doom-modeline-core.el (doom-modeline-set-modeline) (doom-modeline-propertize-icon, doom-modeline--project-root) (doom-modeline--buffer-file-name):
* doom-modeline-env.el (doom-modeline-env--get):
* doom-modeline-segments.el (doom-modeline--buffer-mode-icon) (doom-modeline--buffer-state-icon, doom-modeline--buffer-name) (calc, remote-host, check, workspace-name, input-method, repl) (lsp, doom-modeline--debug-dap): Use `when-let*' instead of in Emacs 31 deprecated `when-let'.

Pacify Emacs 31 compiler warnings

---

README.md
doom-modeline-core.el

When using a variable pitch font in the modeline, the space characters used as padding between segments can be too thin. This new option enables users to override face attributes just for the space characters used as padding in the modeline, such as their font family or height.

Add option to override face attributes for spaces used in padding

---

doom-modeline-env.el

Addresses https://github.com/seagle0128/doom-modeline/issues/765
Below are two examples of projects using different Python versions displayed in the same Emacs session (just switched project).
Project using Python 3.13.x:
Project using Python 3.12.x:

Issue 765: Add uv python version to bootstrap

---

doom-modeline-env.el

I found after 1ce87bea1fcf045d1d2cb52e8e7e2bed7d89bf3a (#766) that `uv.lock` files were spontaneously appearing in my projects. This is because I have `uv` installed and `executable-find` was resolving the binary and running
```
uv run python --version
```
which automatically will materialize a `uv.lock` file (if it's not not present; see the `uv run` [reference](https://docs.astral.sh/uv/reference/cli/#uv-run)). For just detecting the Python version I think this should be avoided; this PR adds the `--no-sync` option to `uv run`; from the CLI docs:
```
--no-sync                                Avoid syncing the virtual environment [env: UV_NO_SYNC=]
```

fix: don't sync `uv.lock` when detecting Python version

---

doom-modeline-env.el

```sh
/tmp/demo/python3 via 🐍 v3.12.9
❯ uname -msr
Darwin 24.3.0 arm64
/tmp/demo/python3 via 🐍 v3.12.9
❯ pwd
/tmp/demo/python3
/tmp/demo/python3 via 🐍 v3.12.9
❯ ll /tmp
lrwxr-xr-x 1 root wheel 11 2025-03-06 18:06 /tmp -> private/tmp
/tmp/demo/python3 via 🐍 v3.12.9
❯ direnv allow .
direnv: loading /private/tmp/demo/python3/.envrc
direnv: export +UV_ACTIVE +VIRTUAL_ENV ~PATH
/tmp/demo/python3 via 🐍 v3.10.16 (python3)
❯ cat ~/.local/share/direnv/allow/e7b1304f1238be3923c42c122b704e033f5b09dfb946c5e8bac837b10f692247
/private/tmp/demo/python3/.envrc
/tmp/demo/python3 via 🐍 v3.10.16 (python3)
❯ direnv exec /tmp/demo/python3 python --version
direnv: error /tmp/demo/python3/.envrc is blocked. Run `direnv allow` to approve its content
/tmp/demo/python3 via 🐍 v3.10.16 (python3)
❯ direnv exec …
```

Fix direnv python version

---

doom-modeline-core.el
doom-modeline.el

Hi. I have noticed in #768 that the font height calculations take up a significant portion of Doom Modeline's CPU/Memory usage. To alleviate this, I have introduced in this PR a cache for the modeline font height.

perf: Cache font height calculation in modeline

---

README.md
doom-modeline-core.el
doom-modeline-segments.el

Add a new customizable variable `doom-modeline-vcs-state-faces-alist`
that allows users to define faces for different version control states.
This replaces hardcoded face mapping in the VCS segment with a more
flexible configuration option.
Also add a default face `doom-modeline-vcs-default` that's used for any
state not explicitly defined in the alist.

Add customizable alist to map VCS states to faces
